### ISSUE TITLE
Problems trying to install climlab with conda-forge

### ISSUE THREAD

**Issue by jokinlasa** [climlab/climlab#178]
Hello,
I'm trying to install climlab for using it in my python project and I'm struggling a little bit. There a couple of Issues reported before that are quite similar, one for  [Google collab](https://github.com/climlab/climlab/issues/175) and the other one for [Binder](https://github.com/brian-rose/ClimateLaboratoryBook/issues/1). The problem is with the Fortran extensions, which I can't import and inizialized correctly. I have installed the dependencies with conda-forge but I still can't make it working. Is there any suggestion or anything else I could try for making it work?

This is the error I'm getting every time.

`C:\Users\Jokin Lasa Escobales\Desktop\Data\Master\Thesis\RRTM\venv\lib\site-packages\climlab\radiation\cam3.py:46: UserWarning: Cannot import and initialize compiled Fortran extension, CAM3 module will not be functional.
  warnings.warn('Cannot import and initialize compiled Fortran extension, CAM3 module will not be functional.')
C:\Users\Jokin Lasa Escobales\Desktop\Data\Master\Thesis\RRTM\venv\lib\site-packages\climlab\radiation\rrtm\rrtmg_lw.py:19: UserWarning: Cannot import and initialize compiled Fortran extension, RRTMG_LW module will not be functional.
  warnings.warn('Cannot import and initialize compiled Fortran extension, RRTMG_LW module will not be functional.')
C:\Users\Jokin Lasa Escobales\Desktop\Data\Master\Thesis\RRTM\venv\lib\site-packages\climlab\radiation\rrtm\rrtmg_sw.py:19: UserWarning: Cannot import and initialize compiled Fortran extension, RRTMG_SW module will not be functional.
  warnings.warn('Cannot import and initialize compiled Fortran extension, RRTMG_SW module will not be functional.')
C:\Users\Jokin Lasa Escobales\Desktop\Data\Master\Thesis\RRTM\venv\lib\site-packages\climlab\convection\emanuel_convection.py:14: UserWarning: Cannot import EmanuelConvection fortran extension, this module will not be functional.
  warnings.warn('Cannot import EmanuelConvection fortran extension, this module will not be functional.')`

Thank you!

**Comment by brian-rose** [comment]
Hi @jokinlasa, I would need more information about your installation in order to help.

Did you follow [these instructions for a self-contained conda environment](https://climlab.readthedocs.io/en/latest/installation.html#installing-into-a-self-contained-conda-environment)?

**Comment by jokinlasa** [comment]
Hi @brian-rose , I wasn't creating the conda enviroment properly. Now everything looks fine!
Thank you for your fast response and your help!
