### ISSUE TITLE
Error in calculation for instantaneous coszen

### ISSUE THREAD

**Issue by SeeSpotRun** [climlab/climlab#192]
I'm pretty sure the '* pi' should be removed
https://github.com/climlab/climlab/blame/9584063ae4dca19f8fb3ffdb5aa399eaff18fdba/climlab/solar/insolation.py#L233

**Comment by brian-rose** [comment]
Thanks for the report @SeeSpotRun, and sorry it's taken quite a while to address this.

The code returns the correct insolation values, but it was confusing because there were two factors of `pi` that canceled each other out.

#206 clarifies things inside the code, but does not change the results.
